#!/bin/bash
# Install RELION Web UI 5 on a Slurm head node (no OOD).
# Run as root. Idempotent. CentOS 7 / RHEL 7-9, Ubuntu 20.04+.
# Reads relion-web-ui.env from the current dir. Run check_environment_headless.sh first.

set -euo pipefail

# Paths (override via env)
BUNDLE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
INSTALL_ROOT="${RELION_INSTALL_ROOT:-/opt/relion-web-ui}"
BACKEND_DIR="${RELION_BACKEND_DIR:-$INSTALL_ROOT/backend}"
FRONTEND_DIR="${RELION_FRONTEND_DIR:-/var/www/relion-web-ui}"
CONDA_ROOT="${RELION_CONDA_ROOT:-/opt/miniconda3}"
CONDA_ENV_NAME="${RELION_CONDA_ENV:-relion-web-ui}"
CONDA_ENV_DIR="$CONDA_ROOT/envs/$CONDA_ENV_NAME"
ENV_FILE_OUT="$INSTALL_ROOT/relion-web-ui.env"
SYSTEMD_UNIT="/etc/systemd/system/relion-web-ui-relion.service"
NGINX_SITE="/etc/nginx/conf.d/relion-web-ui.conf"
HTPASSWD_FILE="/etc/relion-web-ui.htpasswd"
SVC_USER="${RELION_SVC_USER:-relion-web-ui}"

log()  { printf '\033[36m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[33m!!\033[0m  %s\n' "$*" >&2; }
die()  { printf '\033[31mERROR:\033[0m %s\n' "$*" >&2; exit 1; }

# Pre-flight
[[ $EUID -eq 0 ]] || die "must be run as root (sudo)"

if [[ ! -f relion-web-ui.env ]]; then
    die "relion-web-ui.env not found in $PWD
   cp $BUNDLE_DIR/relion-web-ui.env.example relion-web-ui.env && \$EDITOR relion-web-ui.env"
fi

# shellcheck disable=SC1091
set -a; source ./relion-web-ui.env; set +a

required=(RELION_PARTITION RELION_CONTAINER)
missing=()
for k in "${required[@]}"; do
    [[ -n "${!k:-}" ]] || missing+=("$k")
done
[[ ${#missing[@]} -eq 0 ]] || die "relion-web-ui.env missing keys: ${missing[*]}"

[[ -r "$RELION_CONTAINER" ]] || die "RELION_CONTAINER not readable: $RELION_CONTAINER
   Download the RELION Singularity image from https://relion.readthedocs.io/
   and set RELION_CONTAINER in relion-web-ui.env."

# Distro detection
OS_FAMILY=unknown
if command -v yum >/dev/null && [[ -f /etc/redhat-release ]]; then OS_FAMILY=rhel; fi
if command -v dnf >/dev/null && [[ -f /etc/redhat-release ]]; then OS_FAMILY=rhel; fi
if command -v apt-get >/dev/null; then OS_FAMILY=debian; fi
log "OS family: $OS_FAMILY"

# 1. System packages. gcc needed for pip source-builds (numpy etc).
log "installing system packages"
if [[ "$OS_FAMILY" == "rhel" ]]; then
    if ! rpm -q epel-release >/dev/null 2>&1; then
        yum install -y epel-release >/dev/null
    fi
    yum install -y nginx httpd-tools curl tar rsync gcc gcc-c++ make >/dev/null
elif [[ "$OS_FAMILY" == "debian" ]]; then
    apt-get update -qq
    apt-get install -y nginx apache2-utils curl tar rsync build-essential >/dev/null
else
    warn "unknown OS family. Install nginx, htpasswd, gcc yourself."
fi

# 2. Miniconda. CentOS 7 ships Python 3.6, we need 3.11.
if [[ ! -x "$CONDA_ROOT/bin/conda" ]]; then
    log "installing Miniconda to $CONDA_ROOT"
    curl -sSL -o /tmp/miniconda.sh \
        https://repo.anaconda.com/miniconda/Miniconda3-py311_24.1.2-0-Linux-x86_64.sh
    bash /tmp/miniconda.sh -b -p "$CONDA_ROOT"
    rm -f /tmp/miniconda.sh
else
    log "Miniconda already present at $CONDA_ROOT, skipping"
fi

if [[ ! -x "$CONDA_ENV_DIR/bin/python" ]]; then
    log "creating conda env '$CONDA_ENV_NAME'"
    "$CONDA_ROOT/bin/conda" create -y -n "$CONDA_ENV_NAME" python=3.11 >/dev/null
else
    log "conda env '$CONDA_ENV_NAME' exists, skipping"
fi

log "installing python deps"
"$CONDA_ENV_DIR/bin/pip" install --quiet --upgrade pip

# numpy 2.x needs GCC 9+, CentOS 7 has 4.8. Use conda-forge wheels instead.
"$CONDA_ROOT/bin/conda" install -y -n "$CONDA_ENV_NAME" -c conda-forge \
    'numpy<2' matplotlib pillow >/dev/null

# eventlet is pinned in requirements.txt, don't re-pin here.
"$CONDA_ENV_DIR/bin/pip" install --quiet --prefer-binary \
    -r "$BUNDLE_DIR/backend/requirements.txt" \
    "gunicorn>=21"

# 3. Service user
if ! id "$SVC_USER" >/dev/null 2>&1; then
    log "creating user $SVC_USER"
    useradd -r -M -s /usr/sbin/nologin -d "$INSTALL_ROOT" "$SVC_USER"
else
    log "user $SVC_USER exists"
fi

# 4. Layout
log "installing backend to $BACKEND_DIR"
mkdir -p "$BACKEND_DIR" "$INSTALL_ROOT/state" "$INSTALL_ROOT/logs"
rsync -a --delete "$BUNDLE_DIR/backend/" "$BACKEND_DIR/"

log "installing frontend to $FRONTEND_DIR"
mkdir -p "$FRONTEND_DIR"
rsync -a --delete "$BUNDLE_DIR/frontend/" "$FRONTEND_DIR/"

if [[ -d "$BUNDLE_DIR/particle-picker" ]]; then
    log "installing particle-picker"
    mkdir -p "$FRONTEND_DIR/particle-picker"
    rsync -a --delete "$BUNDLE_DIR/particle-picker/" "$FRONTEND_DIR/particle-picker/"
fi

# 5. Env file (systemd EnvironmentFile)
log "writing $ENV_FILE_OUT"
{
    echo "# Generated by install_relion_headless.sh. Do not hand-edit."
    echo "RELION_DEPLOYMENT_MODE=headless"
    echo "RELION_AUTH_MODE=passthrough"
    echo "RELION_CLUSTER_MODE=generic"
    grep -E '^\s*RELION_[A-Z_]+=' relion-web-ui.env
} > "$ENV_FILE_OUT"
chmod 600 "$ENV_FILE_OUT"
chown "$SVC_USER:$SVC_USER" "$ENV_FILE_OUT"

# 6. systemd unit
if [[ -f "$SYSTEMD_UNIT" ]]; then
    cp -a "$SYSTEMD_UNIT" "$SYSTEMD_UNIT.bak-$(date +%s)"
fi
log "writing $SYSTEMD_UNIT"
sed \
    -e "s|__BACKEND_DIR__|$BACKEND_DIR|g" \
    -e "s|__ENV_FILE__|$ENV_FILE_OUT|g" \
    -e "s|__CONDA_ENV__|$CONDA_ENV_DIR|g" \
    "$BUNDLE_DIR/systemd/relion-web-ui-relion.service" > "$SYSTEMD_UNIT"
chmod 644 "$SYSTEMD_UNIT"

# 7. nginx site
if [[ -f "$NGINX_SITE" ]]; then
    cp -a "$NGINX_SITE" "$NGINX_SITE.bak-$(date +%s)"
fi
log "writing $NGINX_SITE"
install -m 644 "$BUNDLE_DIR/nginx/relion-web-ui.conf" "$NGINX_SITE"

# RHEL nginx.conf may already have a listen 80 default_server. Comment it out.
if grep -q "listen\s\+80\s\+default_server" /etc/nginx/nginx.conf 2>/dev/null; then
    warn "existing 'listen 80 default_server' in nginx.conf, commenting out"
    warn "  backup: /etc/nginx/nginx.conf.pre-relion-web-ui"
    cp /etc/nginx/nginx.conf /etc/nginx/nginx.conf.pre-relion-web-ui
    sed -i.bak 's/^\(\s*listen\s\+80\s\+default_server.*\)$/# \1  # commented by relion-web-ui installer/' /etc/nginx/nginx.conf
fi

# 8. htpasswd (basic-auth). Skip if already exists.
ADMIN_USER="${RELION_HEADLESS_ADMIN_USER:-admin}"
if [[ ! -f "$HTPASSWD_FILE" ]]; then
    if [[ -n "${RELION_HEADLESS_ADMIN_PASSWORD:-}" ]]; then
        log "creating $HTPASSWD_FILE with user '$ADMIN_USER' (password from env)"
        htpasswd -bc "$HTPASSWD_FILE" "$ADMIN_USER" "$RELION_HEADLESS_ADMIN_PASSWORD" >/dev/null
    else
        log "creating $HTPASSWD_FILE with user '$ADMIN_USER' (interactive password prompt)"
        htpasswd -c "$HTPASSWD_FILE" "$ADMIN_USER"
    fi
    chmod 640 "$HTPASSWD_FILE"
    chown root:nginx "$HTPASSWD_FILE" 2>/dev/null || chown root:www-data "$HTPASSWD_FILE" 2>/dev/null || true
else
    log "$HTPASSWD_FILE exists, leaving alone"
    log "  add users: htpasswd $HTPASSWD_FILE <username>"
fi

# 9. Permissions
log "setting permissions"
chown -R "$SVC_USER:$SVC_USER" "$INSTALL_ROOT"
find "$BACKEND_DIR" -type d -exec chmod 755 {} +
find "$BACKEND_DIR" -type f -exec chmod 644 {} +
find "$FRONTEND_DIR" -type d -exec chmod 755 {} +
find "$FRONTEND_DIR" -type f -exec chmod 644 {} +

# 10. SELinux
if command -v getenforce >/dev/null && [[ "$(getenforce)" == "Enforcing" ]]; then
    log "SELinux Enforcing, applying booleans"
    setsebool -P httpd_can_network_connect 1 || warn "setsebool failed"
    if command -v chcon >/dev/null; then
        chcon -Rt httpd_sys_content_t "$FRONTEND_DIR" || warn "chcon failed on frontend"
    fi
else
    log "SELinux not enforcing, skipping"
fi

# 11. firewalld (opt-in)
if [[ "${RELION_OPEN_FIREWALL_HTTP:-0}" == "1" ]]; then
    if systemctl is-active --quiet firewalld 2>/dev/null; then
        log "opening firewalld http"
        firewall-cmd --permanent --add-service=http >/dev/null || warn "firewall-cmd failed"
        firewall-cmd --reload >/dev/null || true
    fi
fi

# 12. Start services
log "starting relion-web-ui-relion + nginx"
systemctl daemon-reload
systemctl enable --now relion-web-ui-relion nginx

sleep 2

# 13. Smoke test
log "smoke test"
if curl -sSf -u "$ADMIN_USER:${RELION_HEADLESS_ADMIN_PASSWORD:-}" \
     -o /dev/null -w '  /api/health HTTP %{http_code}\n' \
     http://127.0.0.1/api/health 2>/dev/null; then
    :
else
    curl -sSf -o /dev/null -w '  /healthz HTTP %{http_code}\n' \
        http://127.0.0.1/healthz 2>/dev/null || \
        warn "smoke test failed, check: journalctl -u relion-web-ui-relion"
fi

cat <<EOF

Installed.

  URL:          http://<this-host>/  (user: $ADMIN_USER)
  Logs:         journalctl -u relion-web-ui-relion -f
  Restart:      systemctl restart relion-web-ui-relion
  Add user:     htpasswd $HTPASSWD_FILE <username>
  Backend:      $BACKEND_DIR
  Frontend:     $FRONTEND_DIR
  Env:          $ENV_FILE_OUT

  Issues: https://github.com/Narasimhany/relion-web-ui/issues

EOF
