#!/bin/bash
# Install the RELION 5 OOD app from this bundle.
# Run as root (or with sudo). Reads relion-web-ui.env from the current dir.

set -euo pipefail

BUNDLE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
APP_DIR="${RELION_OOD_APP_DIR:-/var/www/ood/apps/sys/relion_passenger}"
BACKEND_DIR="${RELION_BACKEND_DIR:-/opt/relion5_passenger_backend}"
ENV_FILE_OUT="/etc/ood/config/apps/relion_passenger/env"

if [[ $EUID -ne 0 ]]; then
    echo "ERROR: must be run as root (or sudo)" >&2; exit 1
fi

if [[ ! -f relion-web-ui.env ]]; then
    echo "ERROR: relion-web-ui.env not found in $PWD" >&2
    echo "  cp $BUNDLE_DIR/relion-web-ui.env.example relion-web-ui.env && \$EDITOR relion-web-ui.env" >&2
    exit 1
fi

# Validate required keys
required=(RELION_CLUSTER RELION_PARTITION RELION_CONTAINER)
missing=()
set -a; source ./relion-web-ui.env; set +a
for k in "${required[@]}"; do
    if [[ -z "${!k:-}" ]]; then missing+=("$k"); fi
done
if [[ ${#missing[@]} -gt 0 ]]; then
    echo "ERROR: required keys not set in relion-web-ui.env: ${missing[*]}" >&2; exit 1
fi

echo "==> Installing OOD app to $APP_DIR"
mkdir -p "$APP_DIR"
rsync -a --delete \
    --exclude='backend' \
    --exclude='beta_bundle' \
    "$BUNDLE_DIR/ood_app/" "$APP_DIR/"
# Point Passenger at the customer's backend dir
sed -i "s|__BACKEND_DIR__|$BACKEND_DIR|g" "$APP_DIR/passenger_wsgi.py"

echo "==> Installing Flask backend to $BACKEND_DIR"
mkdir -p "$BACKEND_DIR"
rsync -a --delete "$BUNDLE_DIR/backend/" "$BACKEND_DIR/"

echo "==> Installing frontend assets to $APP_DIR/public"
# OOD/Passenger convention: the app's static assets live under public/, which
# becomes the passenger_document_root. The React build's index.html is what
# the user sees when hitting /pun/sys/relion_passenger/.
mkdir -p "$APP_DIR/public"
rsync -a --delete "$BUNDLE_DIR/frontend/" "$APP_DIR/public/"

echo "==> Writing OOD app env file: $ENV_FILE_OUT"
mkdir -p "$(dirname "$ENV_FILE_OUT")"
{
    echo "# Generated by install_relion_beta.sh -- DO NOT EDIT BY HAND"
    echo "# Edit relion-web-ui.env in the bundle and re-run the installer."
    grep -E '^\s*RELION_[A-Z_]+=' relion-web-ui.env
} > "$ENV_FILE_OUT"
chmod 644 "$ENV_FILE_OUT"

echo "==> Generating PUN nginx app config"
# Without this, OOD's per-user nginx only learns about the app the next time
# the user navigates from the dashboard, which is not guaranteed.
PUN_APPS_DIR=/var/lib/ondemand-nginx/config/apps/sys
mkdir -p "$PUN_APPS_DIR"
cat > "$PUN_APPS_DIR/relion_passenger.conf" <<CONF
location ~ ^/pun/sys/relion_passenger(/.*|\$) {
  error_page 404 @error_404;
  alias $APP_DIR/public\$1;
  passenger_base_uri /pun/sys/relion_passenger;
  passenger_app_root $APP_DIR;
  passenger_document_root $APP_DIR/public;
  passenger_enabled on;
  passenger_app_env production;
}
CONF
chmod 644 "$PUN_APPS_DIR/relion_passenger.conf"
# Reset all PUNs so they pick up the new app config on next request
if command -v /opt/ood/nginx_stage/sbin/nginx_stage >/dev/null; then
    /opt/ood/nginx_stage/sbin/nginx_stage nginx_clean >/dev/null 2>&1 || true
fi

echo "==> Installing Python dependencies"
python3 -m pip install --quiet --upgrade -r "$BACKEND_DIR/requirements.txt" 2>/dev/null || true

echo "==> Setting permissions"
chown -R root:root "$APP_DIR" "$BACKEND_DIR"
# World-readable + traversable so Passenger (running as the OOD user) and the
# per-user Slurm processes can both reach the code. Force 755/644 because
# rsync from a Mac source can preserve restrictive 0600 perms otherwise.
find "$BACKEND_DIR" -type d -exec chmod 755 {} +
find "$BACKEND_DIR" -type f -exec chmod 644 {} +
find "$APP_DIR" -type d -exec chmod 755 {} +
find "$APP_DIR" -type f -exec chmod 644 {} +
# Restart trigger
mkdir -p "$APP_DIR/tmp" && touch "$APP_DIR/tmp/restart.txt"

echo "==> Smoke test: backend imports OK"
python3 -c "
import sys; sys.path.insert(0, '$BACKEND_DIR')
from config import config
assert config.cluster_mode == 'generic', f'expected generic mode, got {config.cluster_mode}'
print(f'  backend OK (cluster_mode={config.cluster_mode}, partition={config.slurm_partition})')
" 2>&1 || { echo "ERROR: backend failed to load -- check $BACKEND_DIR/config.json" >&2; exit 1; }

echo ""
echo "  Done. Open OOD and look for 'RELION 5 Web UI' under Interactive Apps > Cryo-EM."
echo "  If anything misbehaves: $BACKEND_DIR/logs/  +  /var/log/ondemand-nginx/*/error.log"
